import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-tooling-mold-amortization-ownership-recovery",
  "engine": "recovery",
  "title": "Tooling, Mold & Amortization Recovery",
  "shortTitle": "Tooling, Mold and Amortization Recovery",
  "tagline": "Quantify, recover, and prevent financial leakage through tooling, mold & amortization recovery",
  "industry": "Supplier Tooling Financial Control",
  "uiPort": 4611,
  "apiPort": 5611,
  "accent": "#4f46e5",
  "currency": "USD",
  "primaryOutcome": "Tooling, Mold & Amortization Recovery converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect tooling agreements, tools, dies, molds, fixtures, title documents, purchase orders, piece-price amortization, volumes, maintenance, custody, transfer, and residual balances in one accountable recovery workflow.",
  "calculation": {
    "actualKey": "chargedAmount",
    "expectedKey": "supportedAmount",
    "actualLabel": "Tooling Charges and Amortization",
    "expectedLabel": "Supported Remaining Cost",
    "varianceLabel": "Potential recovery or avoided cost",
    "direction": "actual-minus-expected",
    "finding": "Tooling, Mold & Amortization Recovery evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective governing agreement and applicable rules",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare and submit the recovery or correction package",
      "Track counterparty response and reconcile realized outcome"
    ]
  }
},[
feature("tooling-agreement-library","TMA01","Tooling agreement library","Execute tooling agreement library using tooling agreements, tools, dies, molds, fixtures, title documents, purchase orders, piece-price amortization, volumes, maintenance, custody, transfer, and residual balances.","Produce a governed tooling agreement library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Tooling Program","text","Supplier / Tooling Program · Standard Case"],["caseReference","Tooling agreement library Reference","text","TMA01-2026-001"],["chargedAmount","Tooling Charges and Amortization","currency",790000],["supportedAmount","Supported Remaining Cost","currency",679400],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedAmount",subjects:["Tooling agreement library case","Asset serial registry case","Ownership title evidence case","Purchase order reconciliation case","Amortization schedule case"]}),
feature("asset-serial-registry","TMA02","Asset serial registry","Execute asset serial registry using tooling agreements, tools, dies, molds, fixtures, title documents, purchase orders, piece-price amortization, volumes, maintenance, custody, transfer, and residual balances.","Produce a governed asset serial registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Tooling Program","text","Supplier / Tooling Program · Standard Case"],["caseReference","Asset serial registry Reference","text","TMA02-2026-001"],["chargedAmount","Tooling Charges and Amortization","currency",790000],["supportedAmount","Supported Remaining Cost","currency",679400],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedAmount",subjects:["Tooling agreement library case","Asset serial registry case","Ownership title evidence case","Purchase order reconciliation case","Amortization schedule case"]}),
feature("ownership-title-evidence","TMA03","Ownership title evidence","Execute ownership title evidence using tooling agreements, tools, dies, molds, fixtures, title documents, purchase orders, piece-price amortization, volumes, maintenance, custody, transfer, and residual balances.","Produce a governed ownership title evidence decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Tooling Program","text","Supplier / Tooling Program · Standard Case"],["caseReference","Ownership title evidence Reference","text","TMA03-2026-001"],["chargedAmount","Tooling Charges and Amortization","currency",790000],["supportedAmount","Supported Remaining Cost","currency",679400],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedAmount",subjects:["Tooling agreement library case","Asset serial registry case","Ownership title evidence case","Purchase order reconciliation case","Amortization schedule case"]}),
feature("purchase-order-reconciliation","TMA04","Purchase order reconciliation","Execute purchase order reconciliation using tooling agreements, tools, dies, molds, fixtures, title documents, purchase orders, piece-price amortization, volumes, maintenance, custody, transfer, and residual balances.","Produce a governed purchase order reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Tooling Program","text","Supplier / Tooling Program · Standard Case"],["caseReference","Purchase order reconciliation Reference","text","TMA04-2026-001"],["chargedAmount","Tooling Charges and Amortization","currency",790000],["supportedAmount","Supported Remaining Cost","currency",679400],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedAmount",subjects:["Tooling agreement library case","Asset serial registry case","Ownership title evidence case","Purchase order reconciliation case","Amortization schedule case"]}),
feature("amortization-schedule","TMA05","Amortization schedule","Execute amortization schedule using tooling agreements, tools, dies, molds, fixtures, title documents, purchase orders, piece-price amortization, volumes, maintenance, custody, transfer, and residual balances.","Produce a governed amortization schedule decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Tooling Program","text","Supplier / Tooling Program · Standard Case"],["caseReference","Amortization schedule Reference","text","TMA05-2026-001"],["chargedAmount","Tooling Charges and Amortization","currency",790000],["supportedAmount","Supported Remaining Cost","currency",679400],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedAmount",subjects:["Tooling agreement library case","Asset serial registry case","Ownership title evidence case","Purchase order reconciliation case","Amortization schedule case"]}),
feature("piece-price-amortization","TMA06","Piece-price amortization","Execute piece-price amortization using tooling agreements, tools, dies, molds, fixtures, title documents, purchase orders, piece-price amortization, volumes, maintenance, custody, transfer, and residual balances.","Produce a governed piece-price amortization decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Tooling Program","text","Supplier / Tooling Program · Standard Case"],["caseReference","Piece-price amortization Reference","text","TMA06-2026-001"],["chargedAmount","Tooling Charges and Amortization","currency",790000],["supportedAmount","Supported Remaining Cost","currency",679400],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedAmount",subjects:["Tooling agreement library case","Asset serial registry case","Ownership title evidence case","Purchase order reconciliation case","Amortization schedule case"]}),
feature("volume-threshold-monitoring","TMA07","Volume threshold monitoring","Execute volume threshold monitoring using tooling agreements, tools, dies, molds, fixtures, title documents, purchase orders, piece-price amortization, volumes, maintenance, custody, transfer, and residual balances.","Produce a governed volume threshold monitoring decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Tooling Program","text","Supplier / Tooling Program · Standard Case"],["caseReference","Volume threshold monitoring Reference","text","TMA07-2026-001"],["chargedAmount","Tooling Charges and Amortization","currency",790000],["supportedAmount","Supported Remaining Cost","currency",679400],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedAmount",subjects:["Tooling agreement library case","Asset serial registry case","Ownership title evidence case","Purchase order reconciliation case","Amortization schedule case"]}),
feature("duplicate-tooling-detection","TMA08","Duplicate tooling detection","Execute duplicate tooling detection using tooling agreements, tools, dies, molds, fixtures, title documents, purchase orders, piece-price amortization, volumes, maintenance, custody, transfer, and residual balances.","Produce a governed duplicate tooling detection decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Tooling Program","text","Supplier / Tooling Program · Standard Case"],["caseReference","Duplicate tooling detection Reference","text","TMA08-2026-001"],["chargedAmount","Tooling Charges and Amortization","currency",790000],["supportedAmount","Supported Remaining Cost","currency",679400],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedAmount",subjects:["Tooling agreement library case","Asset serial registry case","Ownership title evidence case","Purchase order reconciliation case","Amortization schedule case"]}),
feature("maintenance-responsibility","TMA09","Maintenance responsibility","Execute maintenance responsibility using tooling agreements, tools, dies, molds, fixtures, title documents, purchase orders, piece-price amortization, volumes, maintenance, custody, transfer, and residual balances.","Produce a governed maintenance responsibility decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Tooling Program","text","Supplier / Tooling Program · Standard Case"],["caseReference","Maintenance responsibility Reference","text","TMA09-2026-001"],["chargedAmount","Tooling Charges and Amortization","currency",790000],["supportedAmount","Supported Remaining Cost","currency",679400],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedAmount",subjects:["Tooling agreement library case","Asset serial registry case","Ownership title evidence case","Purchase order reconciliation case","Amortization schedule case"]}),
feature("refurbishment-validation","TMA10","Refurbishment validation","Execute refurbishment validation using tooling agreements, tools, dies, molds, fixtures, title documents, purchase orders, piece-price amortization, volumes, maintenance, custody, transfer, and residual balances.","Produce a governed refurbishment validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Tooling Program","text","Supplier / Tooling Program · Standard Case"],["caseReference","Refurbishment validation Reference","text","TMA10-2026-001"],["chargedAmount","Tooling Charges and Amortization","currency",790000],["supportedAmount","Supported Remaining Cost","currency",679400],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedAmount",subjects:["Tooling agreement library case","Asset serial registry case","Ownership title evidence case","Purchase order reconciliation case","Amortization schedule case"]}),
feature("supplier-custody-tracking","TMA11","Supplier custody tracking","Execute supplier custody tracking using tooling agreements, tools, dies, molds, fixtures, title documents, purchase orders, piece-price amortization, volumes, maintenance, custody, transfer, and residual balances.","Produce a governed supplier custody tracking decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Tooling Program","text","Supplier / Tooling Program · Standard Case"],["caseReference","Supplier custody tracking Reference","text","TMA11-2026-001"],["chargedAmount","Tooling Charges and Amortization","currency",790000],["supportedAmount","Supported Remaining Cost","currency",679400],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedAmount",subjects:["Tooling agreement library case","Asset serial registry case","Ownership title evidence case","Purchase order reconciliation case","Amortization schedule case"]}),
feature("end-of-program-transfer","TMA12","End-of-program transfer","Execute end-of-program transfer using tooling agreements, tools, dies, molds, fixtures, title documents, purchase orders, piece-price amortization, volumes, maintenance, custody, transfer, and residual balances.","Produce a governed end-of-program transfer decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Tooling Program","text","Supplier / Tooling Program · Standard Case"],["caseReference","End-of-program transfer Reference","text","TMA12-2026-001"],["chargedAmount","Tooling Charges and Amortization","currency",790000],["supportedAmount","Supported Remaining Cost","currency",679400],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedAmount",subjects:["Tooling agreement library case","Asset serial registry case","Ownership title evidence case","Purchase order reconciliation case","Amortization schedule case"]}),
feature("residual-balance-recovery","TMA13","Residual balance recovery","Execute residual balance recovery using tooling agreements, tools, dies, molds, fixtures, title documents, purchase orders, piece-price amortization, volumes, maintenance, custody, transfer, and residual balances.","Produce a governed residual balance recovery decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Tooling Program","text","Supplier / Tooling Program · Standard Case"],["caseReference","Residual balance recovery Reference","text","TMA13-2026-001"],["chargedAmount","Tooling Charges and Amortization","currency",790000],["supportedAmount","Supported Remaining Cost","currency",679400],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedAmount",subjects:["Tooling agreement library case","Asset serial registry case","Ownership title evidence case","Purchase order reconciliation case","Amortization schedule case"]}),
feature("tool-return-workflow","TMA14","Tool return workflow","Execute tool return workflow using tooling agreements, tools, dies, molds, fixtures, title documents, purchase orders, piece-price amortization, volumes, maintenance, custody, transfer, and residual balances.","Produce a governed tool return workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Tooling Program","text","Supplier / Tooling Program · Standard Case"],["caseReference","Tool return workflow Reference","text","TMA14-2026-001"],["chargedAmount","Tooling Charges and Amortization","currency",790000],["supportedAmount","Supported Remaining Cost","currency",679400],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedAmount",subjects:["Tooling agreement library case","Asset serial registry case","Ownership title evidence case","Purchase order reconciliation case","Amortization schedule case"]}),
feature("program-supplier-analytics","TMA15","Program supplier analytics","Execute program supplier analytics using tooling agreements, tools, dies, molds, fixtures, title documents, purchase orders, piece-price amortization, volumes, maintenance, custody, transfer, and residual balances.","Produce a governed program supplier analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Supplier / Tooling Program","text","Supplier / Tooling Program · Standard Case"],["caseReference","Program supplier analytics Reference","text","TMA15-2026-001"],["chargedAmount","Tooling Charges and Amortization","currency",790000],["supportedAmount","Supported Remaining Cost","currency",679400],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-09-30"]],{amountField:"chargedAmount",subjects:["Tooling agreement library case","Asset serial registry case","Ownership title evidence case","Purchase order reconciliation case","Amortization schedule case"]})
]);
